### ISSUE TITLE
Skip JsonSchema for 1.24 codegen

### ISSUE THREAD

**Issue by BlankZhu** [BlankZhu/istio-api-rs-codegen#9]
Istio 1.24  add CRD's detailed `status` fields like:

```yaml
      name: v1
      schema:
        openAPIV3Schema:
          properties:
            spec:
            # ...
            status:
              properties:
                conditions:
                  description: Current service state of the resource.
```

So kopium will generate related `Status` struct like:

```
#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema)]
pub struct DestinationRuleStatus {
    /// Current service state of the resource.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
    /// Resource Generation to which the Reconciled Condition refers.
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "observedGeneration")]
    pub observed_generation: Option<IntOrString>,
    /// Includes any errors or warnings detected by Istio's analyzers.
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "validationMessages")]
    pub validation_messages: Option<Vec<DestinationRuleStatusValidationMessages>>,
}
```

The issue is about derive:`JsonSchema` and `kube`'s `Condition` and `IntOrString`. `Condition` and `IntOrString` don't implement `JsonSchema` or `Serialize/Deserialize`, which leads to something like the following while performing `cargo check`:

```txt
the trait bound `k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition: schemars::JsonSchema` is not satisfied
the following other types implement trait `schemars::JsonSchema`:
...
required for `std::vec::Vec<k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition>` to implement `schemars::JsonSchema`
1 redundant requirement hidden
required for `std::option::Option<std::vec::Vec<k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition>>` to implement `schemars::JsonSchema`
```

Since the user of this crate may not be that interested in getting the JSON description from the rust code directly. It's possible to remove the `JsonSchema` in codegen.

The following issue is related on kopium:
kube-rs/kopium#60
